[package]
name = "seahorse-compile-wasm"
version = "0.2.3-nolocalimport" # mirror seahorse-lang version
edition = "2021"
authors = ["Callum McIntyre <callum@pointer.gg>"]
description = "Seahorse compiler for Solana Playground with WASM."
repository = "https://github.com/solana-playground/solana-playground"
license = "GPL-3.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
# File system integration broke WASM: https://github.com/ameliatastic/seahorse-lang/commit/6a9613749e570d1ac85e2e8d0877f8b09b2b0b33
# seahorse-lang = "0.2.3"
seahorse-lang = { git = "https://github.com/ameliatastic/seahorse-lang", rev = "0bc37a40b4a8b983731f2dc9b51ec70d5f6545bf" }
solana-playground-utils-wasm = { path = "../utils/solana-playground-utils" }
wasm-bindgen = "0.2.81"
